version: '3'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-CU17-ubuntu
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: P@ssw0rd

  mysql:
    image: mysql:5.7.28
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test

  postgres:
    image: postgres:11.6-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test

  setup:
    build: ./setup/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mssql
      - mysql
      - postgres
